package org.grid2osm.gisapp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.grid2osm.gisapp.PoiEntities;
import org.grid2osm.gisapp.PoiEntity;
import org.grid2osm.gisapp.LocationEntities;
import org.grid2osm.gisapp.LocationEntity;
import org.grid2osm.gisapp.PhotoEntities;
import org.grid2osm.gisapp.PhotoEntity;
import org.grid2osm.gisapp.PrimitiveAttributesEntity;

import org.grid2osm.gisapp.PoiEntitiesDao;
import org.grid2osm.gisapp.PoiEntityDao;
import org.grid2osm.gisapp.LocationEntitiesDao;
import org.grid2osm.gisapp.LocationEntityDao;
import org.grid2osm.gisapp.PhotoEntitiesDao;
import org.grid2osm.gisapp.PhotoEntityDao;
import org.grid2osm.gisapp.PrimitiveAttributesEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poiEntitiesDaoConfig;
    private final DaoConfig poiEntityDaoConfig;
    private final DaoConfig locationEntitiesDaoConfig;
    private final DaoConfig locationEntityDaoConfig;
    private final DaoConfig photoEntitiesDaoConfig;
    private final DaoConfig photoEntityDaoConfig;
    private final DaoConfig primitiveAttributesEntityDaoConfig;

    private final PoiEntitiesDao poiEntitiesDao;
    private final PoiEntityDao poiEntityDao;
    private final LocationEntitiesDao locationEntitiesDao;
    private final LocationEntityDao locationEntityDao;
    private final PhotoEntitiesDao photoEntitiesDao;
    private final PhotoEntityDao photoEntityDao;
    private final PrimitiveAttributesEntityDao primitiveAttributesEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poiEntitiesDaoConfig = daoConfigMap.get(PoiEntitiesDao.class).clone();
        poiEntitiesDaoConfig.initIdentityScope(type);

        poiEntityDaoConfig = daoConfigMap.get(PoiEntityDao.class).clone();
        poiEntityDaoConfig.initIdentityScope(type);

        locationEntitiesDaoConfig = daoConfigMap.get(LocationEntitiesDao.class).clone();
        locationEntitiesDaoConfig.initIdentityScope(type);

        locationEntityDaoConfig = daoConfigMap.get(LocationEntityDao.class).clone();
        locationEntityDaoConfig.initIdentityScope(type);

        photoEntitiesDaoConfig = daoConfigMap.get(PhotoEntitiesDao.class).clone();
        photoEntitiesDaoConfig.initIdentityScope(type);

        photoEntityDaoConfig = daoConfigMap.get(PhotoEntityDao.class).clone();
        photoEntityDaoConfig.initIdentityScope(type);

        primitiveAttributesEntityDaoConfig = daoConfigMap.get(PrimitiveAttributesEntityDao.class).clone();
        primitiveAttributesEntityDaoConfig.initIdentityScope(type);

        poiEntitiesDao = new PoiEntitiesDao(poiEntitiesDaoConfig, this);
        poiEntityDao = new PoiEntityDao(poiEntityDaoConfig, this);
        locationEntitiesDao = new LocationEntitiesDao(locationEntitiesDaoConfig, this);
        locationEntityDao = new LocationEntityDao(locationEntityDaoConfig, this);
        photoEntitiesDao = new PhotoEntitiesDao(photoEntitiesDaoConfig, this);
        photoEntityDao = new PhotoEntityDao(photoEntityDaoConfig, this);
        primitiveAttributesEntityDao = new PrimitiveAttributesEntityDao(primitiveAttributesEntityDaoConfig, this);

        registerDao(PoiEntities.class, poiEntitiesDao);
        registerDao(PoiEntity.class, poiEntityDao);
        registerDao(LocationEntities.class, locationEntitiesDao);
        registerDao(LocationEntity.class, locationEntityDao);
        registerDao(PhotoEntities.class, photoEntitiesDao);
        registerDao(PhotoEntity.class, photoEntityDao);
        registerDao(PrimitiveAttributesEntity.class, primitiveAttributesEntityDao);
    }
    
    public void clear() {
        poiEntitiesDaoConfig.getIdentityScope().clear();
        poiEntityDaoConfig.getIdentityScope().clear();
        locationEntitiesDaoConfig.getIdentityScope().clear();
        locationEntityDaoConfig.getIdentityScope().clear();
        photoEntitiesDaoConfig.getIdentityScope().clear();
        photoEntityDaoConfig.getIdentityScope().clear();
        primitiveAttributesEntityDaoConfig.getIdentityScope().clear();
    }

    public PoiEntitiesDao getPoiEntitiesDao() {
        return poiEntitiesDao;
    }

    public PoiEntityDao getPoiEntityDao() {
        return poiEntityDao;
    }

    public LocationEntitiesDao getLocationEntitiesDao() {
        return locationEntitiesDao;
    }

    public LocationEntityDao getLocationEntityDao() {
        return locationEntityDao;
    }

    public PhotoEntitiesDao getPhotoEntitiesDao() {
        return photoEntitiesDao;
    }

    public PhotoEntityDao getPhotoEntityDao() {
        return photoEntityDao;
    }

    public PrimitiveAttributesEntityDao getPrimitiveAttributesEntityDao() {
        return primitiveAttributesEntityDao;
    }

}
