package org.grid2osm.gisapp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.grid2osm.gisapp.PoiEntity;
import org.grid2osm.gisapp.LocationTraceEntity;
import org.grid2osm.gisapp.LocationEntity;
import org.grid2osm.gisapp.PhotosEntity;
import org.grid2osm.gisapp.PhotoEntity;
import org.grid2osm.gisapp.PrimitiveAttributesEntity;

import org.grid2osm.gisapp.PoiEntityDao;
import org.grid2osm.gisapp.LocationTraceEntityDao;
import org.grid2osm.gisapp.LocationEntityDao;
import org.grid2osm.gisapp.PhotosEntityDao;
import org.grid2osm.gisapp.PhotoEntityDao;
import org.grid2osm.gisapp.PrimitiveAttributesEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poiEntityDaoConfig;
    private final DaoConfig locationTraceEntityDaoConfig;
    private final DaoConfig locationEntityDaoConfig;
    private final DaoConfig photosEntityDaoConfig;
    private final DaoConfig photoEntityDaoConfig;
    private final DaoConfig primitiveAttributesEntityDaoConfig;

    private final PoiEntityDao poiEntityDao;
    private final LocationTraceEntityDao locationTraceEntityDao;
    private final LocationEntityDao locationEntityDao;
    private final PhotosEntityDao photosEntityDao;
    private final PhotoEntityDao photoEntityDao;
    private final PrimitiveAttributesEntityDao primitiveAttributesEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poiEntityDaoConfig = daoConfigMap.get(PoiEntityDao.class).clone();
        poiEntityDaoConfig.initIdentityScope(type);

        locationTraceEntityDaoConfig = daoConfigMap.get(LocationTraceEntityDao.class).clone();
        locationTraceEntityDaoConfig.initIdentityScope(type);

        locationEntityDaoConfig = daoConfigMap.get(LocationEntityDao.class).clone();
        locationEntityDaoConfig.initIdentityScope(type);

        photosEntityDaoConfig = daoConfigMap.get(PhotosEntityDao.class).clone();
        photosEntityDaoConfig.initIdentityScope(type);

        photoEntityDaoConfig = daoConfigMap.get(PhotoEntityDao.class).clone();
        photoEntityDaoConfig.initIdentityScope(type);

        primitiveAttributesEntityDaoConfig = daoConfigMap.get(PrimitiveAttributesEntityDao.class).clone();
        primitiveAttributesEntityDaoConfig.initIdentityScope(type);

        poiEntityDao = new PoiEntityDao(poiEntityDaoConfig, this);
        locationTraceEntityDao = new LocationTraceEntityDao(locationTraceEntityDaoConfig, this);
        locationEntityDao = new LocationEntityDao(locationEntityDaoConfig, this);
        photosEntityDao = new PhotosEntityDao(photosEntityDaoConfig, this);
        photoEntityDao = new PhotoEntityDao(photoEntityDaoConfig, this);
        primitiveAttributesEntityDao = new PrimitiveAttributesEntityDao(primitiveAttributesEntityDaoConfig, this);

        registerDao(PoiEntity.class, poiEntityDao);
        registerDao(LocationTraceEntity.class, locationTraceEntityDao);
        registerDao(LocationEntity.class, locationEntityDao);
        registerDao(PhotosEntity.class, photosEntityDao);
        registerDao(PhotoEntity.class, photoEntityDao);
        registerDao(PrimitiveAttributesEntity.class, primitiveAttributesEntityDao);
    }
    
    public void clear() {
        poiEntityDaoConfig.getIdentityScope().clear();
        locationTraceEntityDaoConfig.getIdentityScope().clear();
        locationEntityDaoConfig.getIdentityScope().clear();
        photosEntityDaoConfig.getIdentityScope().clear();
        photoEntityDaoConfig.getIdentityScope().clear();
        primitiveAttributesEntityDaoConfig.getIdentityScope().clear();
    }

    public PoiEntityDao getPoiEntityDao() {
        return poiEntityDao;
    }

    public LocationTraceEntityDao getLocationTraceEntityDao() {
        return locationTraceEntityDao;
    }

    public LocationEntityDao getLocationEntityDao() {
        return locationEntityDao;
    }

    public PhotosEntityDao getPhotosEntityDao() {
        return photosEntityDao;
    }

    public PhotoEntityDao getPhotoEntityDao() {
        return photoEntityDao;
    }

    public PrimitiveAttributesEntityDao getPrimitiveAttributesEntityDao() {
        return primitiveAttributesEntityDao;
    }

}
