package org.grid2osm.gisapp;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import org.grid2osm.gisapp.PoiEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table POI_ENTITY.
*/
public class PoiEntityDao extends AbstractDao<PoiEntity, Long> {

    public static final String TABLENAME = "POI_ENTITY";

    /**
     * Properties of entity PoiEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Done = new Property(1, Boolean.class, "done", false, "DONE");
        public final static Property LocationTraceEntityId = new Property(2, long.class, "locationTraceEntityId", false, "LOCATION_TRACE_ENTITY_ID");
        public final static Property PhotosEntityId = new Property(3, long.class, "photosEntityId", false, "PHOTOS_ENTITY_ID");
    };

    private DaoSession daoSession;


    public PoiEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PoiEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'POI_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'DONE' INTEGER," + // 1: done
                "'LOCATION_TRACE_ENTITY_ID' INTEGER NOT NULL ," + // 2: locationTraceEntityId
                "'PHOTOS_ENTITY_ID' INTEGER NOT NULL );"); // 3: photosEntityId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'POI_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PoiEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean done = entity.getDone();
        if (done != null) {
            stmt.bindLong(2, done ? 1l: 0l);
        }
        stmt.bindLong(3, entity.getLocationTraceEntityId());
        stmt.bindLong(4, entity.getPhotosEntityId());
    }

    @Override
    protected void attachEntity(PoiEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PoiEntity readEntity(Cursor cursor, int offset) {
        PoiEntity entity = new PoiEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // done
            cursor.getLong(offset + 2), // locationTraceEntityId
            cursor.getLong(offset + 3) // photosEntityId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PoiEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDone(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setLocationTraceEntityId(cursor.getLong(offset + 2));
        entity.setPhotosEntityId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PoiEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PoiEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLocationTraceEntityDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPhotosEntityDao().getAllColumns());
            builder.append(" FROM POI_ENTITY T");
            builder.append(" LEFT JOIN LOCATION_TRACE_ENTITY T0 ON T.'LOCATION_TRACE_ENTITY_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PHOTOS_ENTITY T1 ON T.'PHOTOS_ENTITY_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PoiEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        PoiEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LocationTraceEntity locationTraceEntity = loadCurrentOther(daoSession.getLocationTraceEntityDao(), cursor, offset);
         if(locationTraceEntity != null) {
            entity.setLocationTraceEntity(locationTraceEntity);
        }
        offset += daoSession.getLocationTraceEntityDao().getAllColumns().length;

        PhotosEntity photosEntity = loadCurrentOther(daoSession.getPhotosEntityDao(), cursor, offset);
         if(photosEntity != null) {
            entity.setPhotosEntity(photosEntity);
        }

        return entity;    
    }

    public PoiEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PoiEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PoiEntity> list = new ArrayList<PoiEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PoiEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PoiEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
